name: Auto Update RSS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 注意这里变了，安装 playwright 及其浏览器内核
      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Script
        run: python main.py

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新每日晨读 RSS"
          file_pattern: 'atom.xml history.json'
